version: '3'

services:
  web:
    build:
      context: GameStore
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mssql-server
    ports:
      - 80:80
  
  mssql-server:
    container_name: sql-server-db
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    environment:
      SA_PASSWORD: "iTechArtGroup11!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
