version: '3'

services:
  web:
    build:
      context: GameStore
      dockerfile: Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: docker
    depends_on:
      - mssql-server
    ports:
      - 8228:80
  
  mssql-server:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    environment:
      SA_PASSWORD: iTechArtGroup11!
      ACCEPT_EULA: Y
    ports:
      - 8229:1433