version: '3'

services:
  web:
    build:
      context: GameStore
      dockerfile: Dockerfile
    restart: always
    environment:
        server: "mssql-server"
        port: "8229"
    depends_on:
      - mssql-server
    ports:
      - 8228:80
  
  mssql-server:
    container_name: sql-server-db
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    restart: always
    environment:
      SA_PASSWORD: "iTechArtGroup11!"
      ACCEPT_EULA: "Y"
    ports:
      - "8229:1433"